spring.application.name=CRUD

#spring.datasource.url=jdbc:mysql://localhost:3306/demo_db
#spring.datasource.user=root
#spring.datasource.password=WhiteDevil@001

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
## JPA
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Swagger UI → http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html



#Port configuration
server.port=8081

#DB configuration
spring.datasource.url=jdbc:mysql://localhost:3306/demo_db
spring.datasource.username=root
spring.datasource.password=WhiteDevil@001
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true